### ISSUE TITLE
Update to the new configuration file

### ISSUE THREAD

**Issue by mikegleasonjr** [sivel/ansible-newrelic#14]
Hi and thank you for the role, very useful.

I would like to set labels in this configuration section:

```
#
# Option : labels
# Value  : A series of label_type/label_value pairings
#          Each item in the pair is separated by a colon
#          Each pair is separated by a semicolon
#          e.g.
#            labels = Environment:Production;DataCenter:EastUS;
# Default: none
#
#labels=label_type:label_value
```

Can you update the template or if you want to make your role future proof, just let users define a dictionary of key values. The config is just key values. You could introduce that without breaking configuration of old clients:

```
newrelic_configs:
  oldcfg1: newrelic_oldcfg1
  oldcfg2: newrelic_oldcfg2
  [...] insert new configs here
```

That way one could create a brand new config

Thank you
